import assert from 'node:assert/strict'
import { readFile } from 'node:fs/promises'

const source = await readFile(new URL('../src/pages/Recovery/index.ux', import.meta.url), 'utf8')

assert.match(source, /round:\s*true/, 'the current 466x466 build paints the round recovery root on its first frame')
assert.match(source, /shapeReady:\s*false/, 'recovery still tracks whether physical screen metadata has arrived')
assert.doesNotMatch(source, /<template>\s*<block if="\{\{shapeReady\}\}">/, 'recovery does not rely on a root condition that the Vela runtime fails to rebuild')
assert.match(source, /const resolveShape = function \(r\) \{[\s\S]*?self\.round = r[\s\S]*?self\.shapeReady = true[\s\S]*?self\._loadRecovery\(\)/, 'recovery applies the resolved shape before rendering recovered content')
assert.match(source, /hydrateApp, isRoundScreen, recoveryPitchView/, 'recovery retains the simulator shape fallback used by the other round pages')
assert.match(source, /var r = res\.screenWidth === res\.screenHeight \|\| isRoundScreen\(res\.screenWidth, res\.screenHeight\)\s*resolveShape\(r\)/, 'recovery classifies equal dimensions as round and tolerates the simulator logical-viewport mismatch')
assert.match(source, /fail: function \(\) \{\s*resolveShape\(isRoundScreen\(0, 0\)\)/, 'recovery uses the existing simulator target when device metadata is unavailable')
assert.match(source, /_shapeFallback = setTimeout\(function \(\) \{\s*resolveShape\(isRoundScreen\(0, 0\)\)/, 'recovery does not fall back to square after a delayed simulator device callback')
assert.doesNotMatch(source, /setTimeout\(function \(\) \{\s*if \(self\.round !== r\)/, 'recovery does not apply the round class after its content has already rendered')
assert.match(source, /class="screen round screen-round"/, 'round recovery paints the root round marker on its first frame')
assert.match(source, /class="fit fit-round"/, 'round recovery paints the safe column on its first frame')
assert.match(source, /class="tag tag-round/, 'round recovery paints the centered title layout directly')
assert.match(source, /class="card card-round"/, 'round recovery paints the circular information card directly')
assert.match(source, /class="field field-round/, 'round recovery paints its round field type scale directly')
assert.match(source, /class="elapsed-row elapsed-row-round"/, 'round recovery stacks the elapsed label and value')
assert.match(source, /class="elapsed-prefix elapsed-prefix-round"/, 'round recovery paints the 13px elapsed label')
assert.match(source, /class="elapsed elapsed-round/, 'round recovery paints the 40px monospaced clock')
assert.match(source, /class="reassure reassure-round"/, 'round recovery paints the centered 13px reassurance')
assert.match(source, /class="spacer spacer-round"/, 'round recovery replaces the flexible square spacer with the measured 24px gap')
assert.match(source, /class="cta cta-round"/, 'round recovery paints the primary action class directly')
assert.match(source, /class="second second-round/, 'round recovery paints the secondary action class directly')
assert.match(source, /class="second second-round second-disabled second-disabled-round"/, 'round corrupt recovery paints the requested disabled opacity')
assert.match(source, /\.screen-round\s*\{[\s\S]*?padding:\s*0;/, 'round recovery starts its safe-area measurement at the 466px viewport edge')
assert.match(source, /\.fit-round\s*\{\s*width:\s*336px;/, 'round recovery uses a 336px safe column')
assert.match(source, /\.tag-round\s*\{[\s\S]*?margin-top:\s*70px;[\s\S]*?font-size:\s*15px;[\s\S]*?text-align:\s*center;/, 'round title clears the top chord and stays centered')
assert.match(source, /\.card-round\s*\{[\s\S]*?width:\s*336px;[\s\S]*?align-items:\s*center;/, 'round card is centered inside the circular safe column')
assert.match(source, /\.field-round\s*\{[\s\S]*?font-size:\s*24px;/, 'round field name uses the requested 24px scale')
assert.match(source, /\.elapsed-row-round\s*\{[\s\S]*?flex-direction:\s*column;[\s\S]*?align-items:\s*center;/, 'round elapsed content is a centered vertical stack')
assert.match(source, /\.elapsed-prefix-round\s*\{[\s\S]*?font-size:\s*13px;/, 'round elapsed label uses the requested 13px scale')
assert.match(source, /\.elapsed-round\s*\{[\s\S]*?font-size:\s*40px;[\s\S]*?font-family:\s*NumBold;/, 'round clock uses the requested 40px monospaced numeral face')
assert.match(source, /\.reassure-round\s*\{[\s\S]*?font-size:\s*13px;/, 'round reassurance uses the requested 13px scale')
assert.match(source, /\.spacer-round\s*\{[\s\S]*?height:\s*24px;/, 'round primary action starts 24px below the card')
assert.match(source, /\.cta-round\s*\{[\s\S]*?width:\s*296px;[\s\S]*?height:\s*56px;[\s\S]*?border-radius:\s*999px;/, 'round primary action stays within the circular bottom chord')
assert.match(source, /\.second-round\s*\{[\s\S]*?width:\s*296px;[\s\S]*?height:\s*52px;[\s\S]*?border-radius:\s*999px;[\s\S]*?margin-top:\s*12px;/, 'round secondary action stays above the circular bottom edge')
assert.match(source, /\.second-disabled-round\s*\{[\s\S]*?opacity:\s*0\.55;/, 'round corrupt recovery communicates the unavailable secondary action')
assert.ok(source.lastIndexOf('.tag-round {') > source.lastIndexOf('.tag {'), 'round title overrides are declared after the untouched square title rule')
assert.ok(source.lastIndexOf('.card-round {') > source.lastIndexOf('.card {'), 'round card overrides are declared after the untouched square card rule')
assert.ok(source.lastIndexOf('.cta-round {') > source.lastIndexOf('.cta {'), 'round primary action overrides are declared after the untouched square action rule')
assert.ok(source.lastIndexOf('.second-round {') > source.lastIndexOf('.second {'), 'round secondary action overrides are declared after the untouched square action rule')
assert.match(source, /\.screen\s*\{[\s\S]*?overflow:\s*hidden;/, 'recovery remains non-scrollable')
assert.match(source, />保存这场比赛<[^]*?>无法继续记录</, 'corrupt recovery preserves the primary/disabled action hierarchy')
assert.doesNotMatch(source, /class="dbg-|\.round \.fit|\.round \.cta|\.round \.second/, 'debug probes and unsupported descendant overrides are removed')

console.log('recovery round layout tests passed')
